sudo: required
services:
  - docker

before_install:
  - docker build -t paulo1410/docker-react -f Dockerfile.dev .

script:
  - docker run paulo1410/docker-react npm run test -- --coverage
  # -- --coverage  faz com que o teste sรณ rodar 1 vez
